// generates the JSON containing the shape vector
// run this with deno

import { Image } from "jsr:@cross/image";
import type { Character } from "./types.ts";
import { rgbaToGrayscale } from "./convert.ts";

const asciiCount = 94;

// load font atlas
const atlas = await Image.decode(await Deno.readFile("./assets/atlas.png"));
function averageInRegion(startx: number, starty: number, width: number, height: number): number {
	let avg = 0;
	let n = 0;
	for(let x = startx; x < startx+width; x++) {
		for(let y = starty; y < starty+height; y++) {
			const pixel = atlas.getPixel(x, y);
			if(pixel == undefined)
				throw new Error(`Pixel ${x} ${y} out of bounds`);
			avg += rgbaToGrayscale(pixel.r/255, pixel.g/255, pixel.b/255, pixel.a/255);
			n++;
		}
	}
	return avg/n;
}
const charWidth = atlas.width/asciiCount;
if(Math.floor(charWidth) != charWidth)
	throw new Error("Character width is not an integer!");
const charHeight = atlas.height;
const chars: Character[] = [];
let maxes = [0, 0, 0, 0, 0, 0]; // maxes for normalization
// get shapes
for(let i = 0; i < asciiCount; i++) {
	const ch = String.fromCharCode(i+32);
	const shape: number[] = [];
	for(let x = 0; x < 2; x++) {
		for(let y = 0; y < 3; y++) {
			shape.push(averageInRegion(i*charWidth+x*Math.floor(charWidth/2), y*Math.floor(charHeight/3), Math.floor(charWidth/2), Math.floor(charHeight/3)));
		}
	}
	for(let i = 0; i < 6; i++) {
		if(shape[i] > maxes[i])
			maxes[i] = shape[i];
	}
	chars.push({
		text: ch,
		shape: shape
	})
}
// normalize
for(const ch of chars) {
	for(let i = 0; i < 6; i++) {
		ch.shape[i] /= maxes[i];
	}
}
// write
await Deno.writeTextFile("./src/generated.ts", `
// File generated by generate.ts
// DO NOT EDIT BY HAND!

import type { Character } from "./types.ts";

export const FONT: Character[] = ${JSON.stringify(chars, null, "\t")};
`.trimStart())
